# Generated by Django 4.2.5 on 2023-09-22 06:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_reason', models.CharField(choices=[('sickness', 'sickness'), ('familydeath', 'familydeath'), ('alarmclockfailure', 'alarmclockfailure'), ('otherreason', 'otherreason')], default='otherreason', max_length=20, verbose_name='justification_absence_reason')),
                ('date_debut', models.DateField(verbose_name='start_absence_justified_date')),
                ('date_fin', models.DateField(verbose_name='end_absence_justified_date')),
                ('proof_document', models.FileField(upload_to='proof_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='proof_of_absence')),
                ('is_validate', models.BooleanField(blank=True, default=None, null=True, verbose_name='is_justification_validated')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifications', to=settings.AUTH_USER_MODEL, verbose_name='related_justification_student')),
            ],
        ),
    ]
