# Generated by Django 4.2.5 on 2023-09-22 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(default='<function uuid4 at 0x000002AC90518540>', max_length=255, unique=True, verbose_name='secret_key_string')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='qr_code_image')),
                ('expiration_time', models.DateTimeField(blank=True, null=True, verbose_name='expiration_time_datetime')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qrcode_s_lesson', to='lessons.lesson', verbose_name='related_qrcode_lesson')),
            ],
        ),
    ]
