# Generated by Django 4.2.5 on 2023-09-22 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='classroom_name')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='lesson_name')),
                ('date_debut', models.DateField(verbose_name='start_date')),
                ('date_fin', models.DateField(verbose_name='end_date')),
                ('description', models.CharField(default='Without descriptions', max_length=500, verbose_name='description')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_s_classroom', to='lessons.classroom', verbose_name='related_lesson_classroom')),
                ('intervening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_s_intervening', to=settings.AUTH_USER_MODEL, verbose_name='related_lesson_intervening')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_s_promotion', to='authentication.promotion', verbose_name='related_lesson_promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False, verbose_name='is_present_bool')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_s_lesson', to='lessons.lesson', verbose_name='related_lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_s_student', to=settings.AUTH_USER_MODEL, verbose_name='related_student')),
            ],
            options={
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
